platform :ios, '10.0'

target 'DemoAlertLegacy' do
  use_frameworks!

pod 'UIAlertControllerShowLegacy'

  target 'DemoAlertLegacyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoAlertLegacyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
